services:
  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - todo-backend

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data

  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/the_database?authSource=admin
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis
