services:
  todo-frontend-dev:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    environment:
      VITE_BACKEND_URL: http://localhost:3000
    volumes:
      - ./todo-frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-frontend-dev
