services:
  todo-frontend-dev:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile.dev
    environment:
      VITE_BACKEND_URL: /api
    volumes:
      - ./todo-frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-frontend-dev
      - todo-backend-dev

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data

  todo-backend-dev:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile.dev
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/the_database?authSource=admin
      REDIS_URL: redis://redis:6379
    volumes:
      - ./todo-backend:/app
      - /app/node_modules
