services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: voldemort
      POSTGRES_PASSWORD: avadakedavra
      POSTGRES_DB: database
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql
